# Site settings
title: Crownstone
email: info@dobots.nl
description: > # this means to ignore newlines until "baseurl:"
  The Crownstone combines indoor localization with automation. iBeacon
  technology makes it possible to interact with people directly using their
  smartphone. Automation allows turning off and on dumb devices.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://crownstone.rocks" # the base hostname & protocol for your site
twitter_username: BotsDo
github_username:  dobots

# Build settings
markdown: kramdown
